name = "age-wisdom-site"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

# 生产环境配置
[env.production]
NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
NEXT_PUBLIC_SITE_URL = "https://your-domain.com"
NEXT_PUBLIC_SITE_NAME = "年龄智慧"

# 预发布环境配置
[env.staging]
NEXT_PUBLIC_SUPABASE_URL = "https://your-staging-project.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-staging-anon-key"
NEXT_PUBLIC_SITE_URL = "https://staging.your-domain.com"
NEXT_PUBLIC_SITE_NAME = "年龄智慧 (测试版)"
